style(dcc-tools): follow shellcheck suggestions

diff --git a/dcc-tools b/dcc-tools
--- a/dcc-tools
+++ b/dcc-tools
@@ -3,7 +3,7 @@
 # Get location of repository by reading the symlink
 # WARNING: It asumes symlink name as `dcc-tools`
 dt_exec_symlink=$(command -v dcc-tools)
-dt_exec_path=$(readlink $dt_exec_symlink)
+dt_exec_path=$(readlink "$dt_exec_symlink")
 TOOLS_DIR=${dt_exec_path%%/dcc-tools}
 
 BIN_DIR="$HOME/.local/bin"
@@ -26,11 +26,11 @@ function myhelp() {
 
 function list_tools() {
 
-    for i in $(find $HOME/.local/bin) ; do
+    for i in $(find "$HOME/.local/bin") ; do
         if [[ -L "$i" ]] ; then
-            og_path=$(readlink $i)
+            og_path=$(readlink "$i")
             if [[ ${og_path%/*} == "$TOOLS_DIR" ]] ; then
-                printf -- "%s\n" ${og_path##*/}
+                printf -- "%s\n" "${og_path##*/}"
             fi
         fi
     done
@@ -46,15 +46,16 @@ function edit_tools() {
         printf -- "ERROR: No tool selected\n" 1>&2
         exit
 
-    elif [[ ! -f "$TOOLS_DIR/$tool" ]] || [[ ! -f "$TOOLS_DIR"/${tool}-fetch ]] ; then
-        printf -- "ERROR: ${tool}: unknown tool\n" 1>&2
+    elif [[ ! -f "$TOOLS_DIR/$tool" ]] || [[ ! -f "$TOOLS_DIR/${tool}-fetch" ]] ; then
+        printf -- 'ERROR: %s: unknown tool\n' "$tool" 1>&2
         exit
     fi
 
     if [[ $mode == "install" ]] ; then
 
         if [[ -f "$TOOLS_DIR/${tool}-fetch" ]] ; then
-            $TOOLS_DIR/${tool}-fetch install "$TOOLS_DIR"
+            TOOL_EXEC="$TOOLS_DIR/${tool}-fetch"
+            $TOOL_EXEC install "$TOOLS_DIR"
         fi
 
         ln -s "$TOOLS_DIR/$tool" "$BIN_DIR/$tool"
@@ -62,7 +63,8 @@ function edit_tools() {
     elif [[ $mode == "remove" ]] ; then
 
         if [[ -f "$TOOLS_DIR/${tool}-fetch" ]] ; then
-            $TOOLS_DIR/${tool}-fetch remove "$TOOLS_DIR"
+            TOOL_EXEC="$TOOLS_DIR/${tool}-fetch"
+            $TOOL_EXEC remove "$TOOLS_DIR"
         fi
         
         rm "$BIN_DIR/$tool"
