fix(dcc-tools): stabilize remove function

diff --git a/dcc-tools b/dcc-tools
--- a/dcc-tools
+++ b/dcc-tools
@@ -131,36 +131,6 @@ function install_tools() {
     ln -sf "${program_path}/${tool}" "${BIN_DIR}/${tool}"
 }
 
-function remove_tools() {
-
-    local tool="$1"
-
-    exec_full_path=$(command -v "$tool")
-    exec_base_path=${exec_full_path##"${TOOLS_DIR}"}
-
-    tool="$exec_base_path"
-
-    # Detect bucket
-    if [[ "$tool" =~ "/" ]] ; then # found bucket
-        bucket="${tool%%/*}"
-        tool="${tool##*/}"
-        program_path="${TOOLS_DIR}/${bucket}"
-
-    else
-        program_path="${TOOLS_DIR}"
-    fi
-
-    # Detect tool-fetch
-    if [[ -f "${program_path}/${tool}-fetch" ]] ; then # found instructions
-        tool_exec="${program_path}/${tool}-fetch"
-        chmod +x "$tool_exec"
-        $tool_exec remove "${program_path}"
-    fi
-
-    rm "${BIN_DIR}/${tool}"
-
-}
-
 function self_remove_tools() {
 
     # delete symlinks
@@ -180,17 +150,40 @@ function self_remove_tools() {
 
 }
 
+
+function remove_tools() {
+
+    local tool="$1"
+
+    if [[ $tool == "dcc-tools" ]] ; then
+        self_remove_tools
+        exit
+    fi
+
+    symlink_bin=$(command -v "$tool")
+
+    if [[ -z $symlink_bin ]] || [[ "$symlink_bin" =~ "/usr/" ]]  ; then
+        printf -- 'ERROR: %s: not found\n' "$tool"
+        exit
+    fi
+
+    fullpath_bin=$(readlink "${symlink_bin}")
+
+    if [[ -f "${fullpath_bin}-fetch" ]] ; then
+        rm ${fullpath_bin}
+    fi
+
+    rm "${BIN_DIR}/${tool}"
+
+}
+
 function edit_tools() {
 
     local mode=$1
     local tool=$2
 
     if [[ -z $tool ]] ; then
-        printf -- "ERROR: No tool selected\n" 1>&2
-        exit
-
-    elif [[ $tool == "dcc-tools" ]] ; then
-        self_remove_tools
+        printf -- "ERROR: no tool selected\n" 1>&2
         exit
 
     elif [[ ! -f "$TOOLS_DIR/$tool" ]] && [[ ! -f "$TOOLS_DIR/${tool}-fetch" ]] ; then
@@ -200,9 +193,6 @@ function edit_tools() {
 
     if [[ $mode == "install" ]] ; then
         install_tools "${tool}"
-
-    elif [[ $mode == "remove" ]] ; then
-        remove_tools "${tool}"
     fi
 
 }
@@ -297,7 +287,7 @@ do
             ;;
         remove)
             shift
-            edit_tools "remove" "$1"
+            remove_tools "$1"
             exit
             ;;
         list)
