feat(dcc-tools): read available scripts from filesystem

diff --git a/dcc-tools b/dcc-tools
--- a/dcc-tools
+++ b/dcc-tools
@@ -37,24 +37,6 @@ function list_tools() {
 
 }
 
-<<<<<<< HEAD
-function destroy_tools() {
-
-    height=$(tput lines)
-    width=$(tput cols)
-
-    clear
-
-    tput cup "$((height/2))" "$((width/2))"
-
-    printf -- "\e[3mI Used the Stones to Destroy the Stones\e[0m\n"
-
-    exit
-
-}
-
-=======
->>>>>>> parent of ea95336 (feat(dcc-tools): catch 'dcc-tools' argument for install|remove)
 function edit_tools() {
 
     local mode=$1
@@ -64,13 +46,9 @@ function edit_tools() {
         printf -- "ERROR: No tool selected\n" 1>&2
         exit
 
-    elif [[ $tool == "imprime" ]] ; then
-        :
-
-    elif [[ $tool == "zola" ]] ; then
-        if [[ ! -f $TOOLS_DIR/zola ]] ; then
-            $TOOLS_DIR/zola-fetch install $TOOLS_DIR
-        fi
+    elif [[ ! -f "$TOOLS_DIR/$tool" ]] ; then
+        printf -- "ERROR: ${tool}: unknown tool\n" 1>&2
+        exit
 
     else
         printf -- "ERROR: ${tool}: unknown tool\n" 1>&2
@@ -78,10 +56,20 @@ function edit_tools() {
     fi
 
     if [[ $mode == "install" ]] ; then
-        ln -s $TOOLS_DIR/$tool $BIN_DIR/$tool
+
+        if [[ -f "$TOOLS_DIR/${tool}-fetch" ]] ; then
+            $TOOLS_DIR/${tool}-fetch install "$TOOLS_DIR"
+        fi
+
+        ln -s "$TOOLS_DIR/$tool" "$BIN_DIR/$tool"
 
     elif [[ $mode == "remove" ]] ; then
-        rm $BIN_DIR/$tool
+
+        if [[ -f "$TOOLS_DIR/${tool}-fetch" ]] ; then
+            $TOOLS_DIR/${tool}-fetch remove "$TOOLS_DIR"
+        fi
+        
+        rm "$BIN_DIR/$tool"
     fi
 
 }
@@ -115,12 +103,12 @@ do
             ;;
         install)
             shift
-            edit_tools "install" $1
+            edit_tools "install" "$1"
             exit
             ;;
         remove)
             shift
-            edit_tools "remove" $1
+            edit_tools "remove" "$1"
             exit
             ;;
         list)
